# -*- coding: utf-8 -*-
"""cs119- hw3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBHaWM9HofGaKac632VmoyUdWCUPEOqH
"""

#!/usr/bin/env python3
import pandas as pd
def rot_pandas(self, rot_num = None):
  if rot_num == None:
    output = self.iloc[::-1]
  else:
    rot_num = rot_num % len(self)
    output = pd.concat([ser.iloc[-rot_num:], ser.iloc[:-rot_num]],ignore_index=True)
  return output

pd.Series.ɸ = rot_pandas
ser = pd.Series([1,2,3,4,5])
print (ser.ɸ(1).to_list())  # prints [5, 1, 2, 3, 4]
print (ser.ɸ(2).to_list())  # prints [4, 5, 1, 2, 3]
print (ser.ɸ(10).to_list()) # prints [1, 2, 3, 4, 5]
print (ser.ɸ().to_list()) # prints [5, 4, 3, 2, 1]